/// Flutter icons CarIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CarIcons
///      fonts:
///       - asset: fonts/CarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CarIcons {
  CarIcons._();

  static const _kFontFam = 'CarIcons';

  static const IconData taxi = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData parking = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData brake = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData steering_wheel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cab = const IconData(0xe805, fontFamily: _kFontFam);
}
